In [1]:
import psycopg2
from psycopg2 import OperationalError

In [43]:
def create_connection():
    """Estabelece uma conexão com o banco de dados PostgreSQL."""
    try:
        connection = psycopg2.connect(
            user="postgres",
            password="admin",
            host="localhost",
            port="5432",
            database="postgres"
        )
        print("Conexão com o banco de dados estabelecida com sucesso!")
        return connection

    except OperationalError as e:
        print(f"Erro ao conectar ao banco de dados: {e}")
        return None

def close_connection(connection):
    """Fecha a conexão com o banco de dados."""
    if connection:
        connection.close()
        print("Conexão com o banco de dados fechada.")

In [68]:
# Fechar a conexão
close_connection(conn)

Conexão com o banco de dados fechada.


In [69]:
# Criar uma conexão
conn = create_connection()

# Criar um cursor
cursor = conn.cursor()

Conexão com o banco de dados estabelecida com sucesso!


In [ ]:
cursor.execute('''CREATE TABLE EMPREGADO (
  ssn char(9) NOT NULL,
  pnome varchar(30) NOT NULL,
  inicialm char(1) default NULL,
  unome varchar(30) NOT NULL,
  sexo char(1) NOT NULL,
  endereco varchar(50) default NULL,
  datanasc date default NULL,
  superssn char(9) default NULL,
  dno char(1) NOT NULL,
  salario float default NULL,
  PRIMARY KEY  (ssn)
) ;
''')

In [ ]:
cursor.execute("INSERT INTO EMPREGADO VALUES ('123456789', 'Joao', 'B', 'Souza', 'M', 'R. 24 de maio, 1500 - Curitiba - PR', '1965-01-09', '333445555', '5', '30000.00');")
cursor.execute("INSERT INTO EMPREGADO VALUES ('333445555', 'Fabio', 'T', 'Will', 'M', 'R. Alagoas, 325 - Curitiba - PR', '1955-12-08', '888665555', '5', '40000.00');")
cursor.execute("INSERT INTO EMPREGADO VALUES ('999887777', 'Alice', 'J', 'Zebra', 'F', 'R. Ribeira, 98 - Pinhais - PR', '1968-01-19', '987654321', '4', '25000.00');")
cursor.execute("INSERT INTO EMPREGADO VALUES ('987654321', 'Jennifer', 'S', 'Wallace', 'F', 'R. Berry, 291 - Colombo - PR', '1941-06-20', '888665555', '4', '43000.00');")
cursor.execute("INSERT INTO EMPREGADO VALUES ('666884444', 'Ricardo', 'K', 'Nantes', 'M', 'Av. Figueira, 55 - Almirante Tamandare - PR', '1962-09-15', '333445555', '5', '38000.00');")
cursor.execute("INSERT INTO EMPREGADO VALUES ('453453453', 'Jussara', 'A', 'Pereira', 'F', 'Trav. da Lapa, 23 - Curitiba - PR', '1972-07-31', '333445555', '5', '25000.00');")
cursor.execute("INSERT INTO EMPREGADO VALUES ('987987987', 'Alberto', 'V', 'Medeiros', 'M', 'R. Ceará, 1245 - Curitiba - PR', '1969-03-29', '987654321', '4', '25000.00');")
cursor.execute("INSERT INTO EMPREGADO VALUES ('888665555', 'Joaquim', 'E', 'Brito', 'M', 'R. Stone, 450 - Curitiba - PR', '1937-11-10', null, '1', '55000.00');")

In [ ]:
cursor.execute('''CREATE TABLE DEPARTAMENTO (
  dnumero char(1) NOT NULL,
  dnome varchar(30) NOT NULL,
  gerssn char(9) NOT NULL,
  gerdatainicio date NOT NULL,
  PRIMARY KEY  (dnumero)
) ;
''')

In [ ]:
cursor.execute("INSERT INTO DEPARTAMENTO VALUES ('5', 'Pesquisa', '333445555', '1988-05-22');")
cursor.execute("INSERT INTO DEPARTAMENTO VALUES ('4', 'Administracao', '987654321', '1995-01-01');")
cursor.execute("INSERT INTO DEPARTAMENTO VALUES ('1', 'Sede Administrativa', '888665555', '1981-06-19');")

In [ ]:
cursor.execute('''
CREATE TABLE DEPENDENTE (
  essn char(9) NOT NULL,
  nomedep varchar(30) NOT NULL default '',
  sexodep char(1) NOT NULL,
  datanascdep date NOT NULL,
  parentesco varchar(30) NOT NULL,
  PRIMARY KEY  (essn,nomedep)
) ;
''')

In [ ]:
cursor.execute("INSERT INTO DEPENDENTE VALUES ('333445555', 'Alice', 'F', '1986-04-05', 'FILHA');")
cursor.execute("INSERT INTO DEPENDENTE VALUES ('333445555', 'Teodoro', 'M', '1983-10-25', 'FILHO');")
cursor.execute("INSERT INTO DEPENDENTE VALUES ('333445555', 'Joana', 'F', '1958-05-03', 'CONJUGE');")
cursor.execute("INSERT INTO DEPENDENTE VALUES ('987654321', 'Abdala', 'M', '1942-02-28', 'CONJUGE');")
cursor.execute("INSERT INTO DEPENDENTE VALUES ('123456789', 'Michel', 'M', '1988-01-04', 'FILHO');")
cursor.execute("INSERT INTO DEPENDENTE VALUES ('123456789', 'Alice', 'F', '1988-12-30', 'FILHA');")
cursor.execute("INSERT INTO DEPENDENTE VALUES ('123456789', 'Elizabete', 'F', '1967-05-05', 'CONJUGE');")

In [ ]:
cursor.execute('''
CREATE TABLE LOCALIZACAO (
  dnum char(1) NOT NULL,
  dlocalizacao varchar(30) NOT NULL,
  PRIMARY KEY  (dnum,dlocalizacao)
) ;
''')

In [ ]:
cursor.execute("INSERT INTO LOCALIZACAO VALUES ('1', 'Curitiba');")
cursor.execute("INSERT INTO LOCALIZACAO VALUES ('4', 'Colombo');")
cursor.execute("INSERT INTO LOCALIZACAO VALUES ('5', 'Araucaria');")
cursor.execute("INSERT INTO LOCALIZACAO VALUES ('5', 'Curitiba');")
cursor.execute("INSERT INTO LOCALIZACAO VALUES ('5', 'Pinhais');")

In [ ]:
cursor.execute('''
CREATE TABLE PROJETO (
  pnumero char(2) NOT NULL,
  pjnome varchar(30) NOT NULL,
  plocal varchar(30) NOT NULL,
  dnum char(1) NOT NULL,
  PRIMARY KEY  (pnumero)
) ;
''')

In [ ]:
cursor.execute("INSERT INTO PROJETO VALUES ('1', 'ProdutoX', 'Pinhais', '5');")
cursor.execute("INSERT INTO PROJETO VALUES ('2', 'ProdutoY', 'Araucaria', '5');")
cursor.execute("INSERT INTO PROJETO VALUES ('3', 'ProdutoZ', 'Curitiba', '5');")
cursor.execute("INSERT INTO PROJETO VALUES ('10', 'Automatizacao', 'Pinhais', '4');")
cursor.execute("INSERT INTO PROJETO VALUES ('20', 'Reorganizacao', 'Curitiba', '1');")
cursor.execute("INSERT INTO PROJETO VALUES ('30', 'Novos Beneficios', 'Pinhais', '4');")

In [ ]:
cursor.execute('''
CREATE TABLE TRABALHA (
  essn char(9) NOT NULL,
  pno char(2) NOT NULL,
  horas float default NULL,
  PRIMARY KEY  (essn,pno)
) ;
''')

In [ ]:
cursor.execute("INSERT INTO TRABALHA VALUES ('123456789', '1', '32.5');")
cursor.execute("INSERT INTO TRABALHA VALUES ('123456789', '2', '7.5');")
cursor.execute("INSERT INTO TRABALHA VALUES ('666884444', '3', '40');")
cursor.execute("INSERT INTO TRABALHA VALUES ('453453453', '1', '20');")
cursor.execute("INSERT INTO TRABALHA VALUES ('453453453', '2', '20');")
cursor.execute("INSERT INTO TRABALHA VALUES ('333445555', '2', '10');")
cursor.execute("INSERT INTO TRABALHA VALUES ('333445555', '3', '10');")
cursor.execute("INSERT INTO TRABALHA VALUES ('333445555', '10', '10');")
cursor.execute("INSERT INTO TRABALHA VALUES ('333445555', '20', '10');")
cursor.execute("INSERT INTO TRABALHA VALUES ('999887777', '30', '30');")
cursor.execute("INSERT INTO TRABALHA VALUES ('999887777', '10', '10');")
cursor.execute("INSERT INTO TRABALHA VALUES ('987987987', '10', '35');")
cursor.execute("INSERT INTO TRABALHA VALUES ('987987987', '30', '5');")
cursor.execute("INSERT INTO TRABALHA VALUES ('987654321', '30', '20');")
cursor.execute("INSERT INTO TRABALHA VALUES ('987654321', '20', '15');")
cursor.execute("INSERT INTO TRABALHA VALUES ('888665555', '20', null);")

In [ ]:
cursor.execute("ALTER TABLE EMPREGADO ADD CONSTRAINT fk_empregado_empregado  FOREIGN KEY (superssn) REFERENCES  EMPREGADO (ssn);")
cursor.execute("ALTER TABLE EMPREGADO ADD CONSTRAINT fk_empregado_departamento FOREIGN KEY  (dno) REFERENCES  DEPARTAMENTO (dnumero) ;")
cursor.execute("ALTER TABLE DEPARTAMENTO ADD CONSTRAINT fk_departamento_empregado FOREIGN KEY (gerssn) REFERENCES  EMPREGADO (ssn) ;")
cursor.execute("ALTER TABLE DEPENDENTE ADD CONSTRAINT fk_dependente_empregado FOREIGN KEY (essn) REFERENCES EMPREGADO (ssn) ;")
cursor.execute("ALTER TABLE LOCALIZACAO ADD CONSTRAINT fk_localizacao_departamento FOREIGN KEY (dnum) REFERENCES  DEPARTAMENTO (dnumero) ;")
cursor.execute("ALTER TABLE PROJETO ADD CONSTRAINT fk_projeto_departamento FOREIGN KEY (dnum) REFERENCES  DEPARTAMENTO (dnumero) ;")
cursor.execute("ALTER TABLE TRABALHA ADD CONSTRAINT fk_trabalha_empregado FOREIGN KEY (essn) REFERENCES  EMPREGADO (ssn) ;")
cursor.execute("ALTER TABLE TRABALHA ADD CONSTRAINT fk_trabalha_projeto FOREIGN KEY (pno) REFERENCES  PROJETO (pnumero) ;")
               
# Commitar as transações
conn.commit()

a) Insira >‘943775543’, ‘Roberto’, ‘F’, ‘Silva’, ‘M’, ‘Rua X, 22 – Araucária – PR’, ‘1952-06-21’,
‘888665555’, ‘1’, 58000< em EMPREGADO.

In [38]:
cursor.execute("INSERT INTO EMPREGADO VALUES ('943775543', 'Roberto', 'F', 'Silva', 'M', 'Rua X, 22 – Araucária – PR', '1952-06-21', '888665555', '1', '58000');")
# Confirmar a transação
conn.commit()

In [45]:
cursor.execute("SELECT * FROM EMPREGADO;")
rows = cursor.fetchall()

# Iterar sobre os resultados e imprimir
for row in rows:
    print(row)

('123456789', 'Joao', 'B', 'Souza', 'M', 'R. 24 de maio, 1500 - Curitiba - PR', datetime.date(1965, 1, 9), '333445555', '5', 30000.0)
('333445555', 'Fabio', 'T', 'Will', 'M', 'R. Alagoas, 325 - Curitiba - PR', datetime.date(1955, 12, 8), '888665555', '5', 40000.0)
('999887777', 'Alice', 'J', 'Zebra', 'F', 'R. Ribeira, 98 - Pinhais - PR', datetime.date(1968, 1, 19), '987654321', '4', 25000.0)
('987654321', 'Jennifer', 'S', 'Wallace', 'F', 'R. Berry, 291 - Colombo - PR', datetime.date(1941, 6, 20), '888665555', '4', 43000.0)
('666884444', 'Ricardo', 'K', 'Nantes', 'M', 'Av. Figueira, 55 - Almirante Tamandare - PR', datetime.date(1962, 9, 15), '333445555', '5', 38000.0)
('453453453', 'Jussara', 'A', 'Pereira', 'F', 'Trav. da Lapa, 23 - Curitiba - PR', datetime.date(1972, 7, 31), '333445555', '5', 25000.0)
('987987987', 'Alberto', 'V', 'Medeiros', 'M', 'R. Ceará, 1245 - Curitiba - PR', datetime.date(1969, 3, 29), '987654321', '4', 25000.0)
('888665555', 'Joaquim', 'E', 'Brito', 'M', 'R. St

b) Insira >‘4’, ProdutoA’, ‘Araucaria’, ‘2’< em PROJETO

In [41]:
cursor.execute("INSERT INTO PROJETO VALUES ('4', 'ProdutoA', 'Araucaria', '2');")

ForeignKeyViolation: ERRO:  inserção ou atualização em tabela "projeto" viola restrição de chave estrangeira "fk_projeto_departamento"
DETAIL:  Chave (dnum)=(2) não está presente na tabela "departamento".


In [47]:
cursor.execute("SELECT * FROM DEPARTAMENTO;")
rows = cursor.fetchall()

# Iterar sobre os resultados e imprimir
for row in rows:
    print(row)

('5', 'Pesquisa', '333445555', datetime.date(1988, 5, 22))
('4', 'Administracao', '987654321', datetime.date(1995, 1, 1))
('1', 'Sede Administrativa', '888665555', datetime.date(1981, 6, 19))


A tabela departamento não possui nenhum registro dnumero igual a 2, e esse atributo é chave primária, portanto ao tentar inserir um novo registro em projeto, com dnumero igual a 2, o banco de dados irá retorna um erro de chave estrangeira, pois não existe um departamento com dnumero igual a 2.

c) Insira >‘4’, ‘Produção’, ‘943775543’, ‘1998-10-01’< em DEPARTAMENTO.

In [50]:
cursor.execute("INSERT INTO DEPARTAMENTO VALUES ('4', 'Produção', '943775543', '1998-10-01');")
# Confirmar a transação
conn.commit()

UniqueViolation: ERRO:  duplicar valor da chave viola a restrição de unicidade "departamento_pkey"
DETAIL:  Chave (dnumero)=(4) já existe.


dnumero é chave primária na tabela departamento, e o valor 4 já existe, portanto ao tentar inserir um novo registro em departamento, com dnumero igual a 4, o banco de dados irá retorna um erro de chave primária, pois já existe um departamento com dnumero igual a 4.

d) Insira >‘677678989’, null, 40.0< em TRABALHA

In [54]:
cursor.execute("INSERT INTO TRABALHA VALUES ('677678989', 'null', '40.0');")
# Confirmar a transação
conn.commit()

StringDataRightTruncation: ERRO:  valor é muito longo para tipo character(2)


O campo pno aceita apenas char com 2 caracteres, e o valor inserido 'null' possui 4 caracteres, portanto o banco de dados irá retornar um erro de tipo de dados.

e) Insira >‘453453453’, ‘Joao’, ‘M’, ‘1970-12-12’, ‘CONJUGE’< em DEPENDENTE.

In [57]:
cursor.execute("INSERT INTO DEPENDENTE VALUES ('453453453', 'Joao', 'M', '1970-12-12', 'CONJUGE');")
# Confirmar a transação
conn.commit()

In [58]:
cursor.execute("SELECT * FROM DEPENDENTE;")
rows = cursor.fetchall()

# Iterar sobre os resultados e imprimir
for row in rows:
    print(row)

('333445555', 'Alice', 'F', datetime.date(1986, 4, 5), 'FILHA')
('333445555', 'Teodoro', 'M', datetime.date(1983, 10, 25), 'FILHO')
('333445555', 'Joana', 'F', datetime.date(1958, 5, 3), 'CONJUGE')
('987654321', 'Abdala', 'M', datetime.date(1942, 2, 28), 'CONJUGE')
('123456789', 'Michel', 'M', datetime.date(1988, 1, 4), 'FILHO')
('123456789', 'Alice', 'F', datetime.date(1988, 12, 30), 'FILHA')
('123456789', 'Elizabete', 'F', datetime.date(1967, 5, 5), 'CONJUGE')
('453453453', 'Joao', 'M', datetime.date(1970, 12, 12), 'CONJUGE')


f) Remova as tuplas de TRABALHA com ESSN = ‘333445555’

In [59]:
cursor.execute("DELETE FROM TRABALHA WHERE essn = '333445555';")
# Confirmar a transação
conn.commit()

In [60]:
cursor.execute("SELECT * FROM TRABALHA;")
rows = cursor.fetchall()

# Iterar sobre os resultados e imprimir
for row in rows:
    print(row)

('123456789', '1 ', 32.5)
('123456789', '2 ', 7.5)
('666884444', '3 ', 40.0)
('453453453', '1 ', 20.0)
('453453453', '2 ', 20.0)
('999887777', '30', 30.0)
('999887777', '10', 10.0)
('987987987', '10', 35.0)
('987987987', '30', 5.0)
('987654321', '30', 20.0)
('987654321', '20', 15.0)
('888665555', '20', None)


g) Remova a tupla de EMPREGADO com SSN = ‘987654321’.

In [61]:
cursor.execute("DELETE FROM EMPREGADO WHERE ssn = '987654321';")
# Confirmar a transação
conn.commit()

ForeignKeyViolation: ERRO:  atualização ou exclusão em tabela "empregado" viola restrição de chave estrangeira "fk_empregado_empregado" em "empregado"
DETAIL:  Chave (ssn)=(987654321) ainda é referenciada pela tabela "empregado".


In [64]:
cursor.execute("SELECT * FROM EMPREGADO;")
rows = cursor.fetchall()

# Iterar sobre os resultados e imprimir
for row in rows:
    print(row)

('123456789', 'Joao', 'B', 'Souza', 'M', 'R. 24 de maio, 1500 - Curitiba - PR', datetime.date(1965, 1, 9), '333445555', '5', 30000.0)
('333445555', 'Fabio', 'T', 'Will', 'M', 'R. Alagoas, 325 - Curitiba - PR', datetime.date(1955, 12, 8), '888665555', '5', 40000.0)
('999887777', 'Alice', 'J', 'Zebra', 'F', 'R. Ribeira, 98 - Pinhais - PR', datetime.date(1968, 1, 19), '987654321', '4', 25000.0)
('987654321', 'Jennifer', 'S', 'Wallace', 'F', 'R. Berry, 291 - Colombo - PR', datetime.date(1941, 6, 20), '888665555', '4', 43000.0)
('666884444', 'Ricardo', 'K', 'Nantes', 'M', 'Av. Figueira, 55 - Almirante Tamandare - PR', datetime.date(1962, 9, 15), '333445555', '5', 38000.0)
('453453453', 'Jussara', 'A', 'Pereira', 'F', 'Trav. da Lapa, 23 - Curitiba - PR', datetime.date(1972, 7, 31), '333445555', '5', 25000.0)
('987987987', 'Alberto', 'V', 'Medeiros', 'M', 'R. Ceará, 1245 - Curitiba - PR', datetime.date(1969, 3, 29), '987654321', '4', 25000.0)
('888665555', 'Joaquim', 'E', 'Brito', 'M', 'R. St

O atributo ssn da tabela empregado, é chave primária e estrangeira, sendo referenciada por superssn na mesma tabela, e por essn na tabela trabalha, portanto ao tentar remover a tupla de empregado com ssn igual a 987654321, o banco de dados irá retornar um erro de chave estrangeira, pois existem registros na mesma tabela e em outras tabelas que referenciam essa tupla.

h) Remova a tupla de PROJETO com PJNOME = ‘ProdutoX’

In [67]:
cursor.execute("DELETE FROM PROJETO WHERE PJNOME = 'ProdutoX';")
# Confirmar a transação
conn.commit()

ForeignKeyViolation: ERRO:  atualização ou exclusão em tabela "projeto" viola restrição de chave estrangeira "fk_trabalha_projeto" em "trabalha"
DETAIL:  Chave (pnumero)=(1 ) ainda é referenciada pela tabela "trabalha".


In [71]:
cursor.execute("SELECT * FROM PROJETO;")
rows = cursor.fetchall()

# Iterar sobre os resultados e imprimir
for row in rows:
    print(row)

('1 ', 'ProdutoX', 'Pinhais', '5')
('2 ', 'ProdutoY', 'Araucaria', '5')
('3 ', 'ProdutoZ', 'Curitiba', '5')
('10', 'Automatizacao', 'Pinhais', '4')
('20', 'Reorganizacao', 'Curitiba', '1')
('30', 'Novos Beneficios', 'Pinhais', '4')


In [70]:
cursor.execute("SELECT * FROM TRABALHA;")
rows = cursor.fetchall()

# Iterar sobre os resultados e imprimir
for row in rows:
    print(row)

('123456789', '1 ', 32.5)
('123456789', '2 ', 7.5)
('666884444', '3 ', 40.0)
('453453453', '1 ', 20.0)
('453453453', '2 ', 20.0)
('999887777', '30', 30.0)
('999887777', '10', 10.0)
('987987987', '10', 35.0)
('987987987', '30', 5.0)
('987654321', '30', 20.0)
('987654321', '20', 15.0)
('888665555', '20', None)


Pnumero é chave primária em projeto, e chave estrangeira em trabalha, portanto ao tentar remover a tupla de projeto com pjnome igual a ProdutoX, o banco de dados irá retornar um erro de chave estrangeira, pois existem registros na tabela trabalha que referenciam essa tupla.

i) Modifique o GERSSN e GERDATAINICIO da tupla de DEPARTAMENTO com DNUMERO = 5
para ‘123456789’ e ‘1999-01-10’, respectivamente.

In [72]:
cursor.execute("UPDATE DEPARTAMENTO SET GERSSN = '123456789' , GERDATAINICIO ='1999-01-10'  WHERE DNUMERO = '5';")
# Confirmar a transação
conn.commit()

In [73]:
cursor.execute("SELECT * FROM DEPARTAMENTO;")
rows = cursor.fetchall()

# Iterar sobre os resultados e imprimir
for row in rows:
    print(row)

('4', 'Administracao', '987654321', datetime.date(1995, 1, 1))
('1', 'Sede Administrativa', '888665555', datetime.date(1981, 6, 19))
('5', 'Pesquisa', '123456789', datetime.date(1999, 1, 10))


j) Modifique o atributo SUPERSSN da tupla EMPREGADO com SSN = ‘999887777’ para
‘943775543’.

In [74]:
cursor.execute("UPDATE EMPREGADO SET SUPERSSN = '943775543' WHERE SSN = '999887777';")
# Confirmar a transação
conn.commit()

In [75]:
cursor.execute("SELECT * FROM EMPREGADO;")
rows = cursor.fetchall()

# Iterar sobre os resultados e imprimir
for row in rows:
    print(row)

('123456789', 'Joao', 'B', 'Souza', 'M', 'R. 24 de maio, 1500 - Curitiba - PR', datetime.date(1965, 1, 9), '333445555', '5', 30000.0)
('333445555', 'Fabio', 'T', 'Will', 'M', 'R. Alagoas, 325 - Curitiba - PR', datetime.date(1955, 12, 8), '888665555', '5', 40000.0)
('987654321', 'Jennifer', 'S', 'Wallace', 'F', 'R. Berry, 291 - Colombo - PR', datetime.date(1941, 6, 20), '888665555', '4', 43000.0)
('666884444', 'Ricardo', 'K', 'Nantes', 'M', 'Av. Figueira, 55 - Almirante Tamandare - PR', datetime.date(1962, 9, 15), '333445555', '5', 38000.0)
('453453453', 'Jussara', 'A', 'Pereira', 'F', 'Trav. da Lapa, 23 - Curitiba - PR', datetime.date(1972, 7, 31), '333445555', '5', 25000.0)
('987987987', 'Alberto', 'V', 'Medeiros', 'M', 'R. Ceará, 1245 - Curitiba - PR', datetime.date(1969, 3, 29), '987654321', '4', 25000.0)
('888665555', 'Joaquim', 'E', 'Brito', 'M', 'R. Stone, 450 - Curitiba - PR', datetime.date(1937, 11, 10), None, '1', 55000.0)
('943775543', 'Roberto', 'F', 'Silva', 'M', 'Rua X, 22

l) Modifique o atributo HORAS da tupla de TRABALHA com ESSN = ‘999887777’ e PNO = ‘10’
para 5,0.

In [76]:
cursor.execute("UPDATE TRABALHA SET HORAS = '5' WHERE ESSN = '999887777' AND PNO = '10';")
# Confirmar a transação
conn.commit()

In [77]:
cursor.execute("SELECT * FROM TRABALHA;")
rows = cursor.fetchall()

# Iterar sobre os resultados e imprimir
for row in rows:
    print(row)

('123456789', '1 ', 32.5)
('123456789', '2 ', 7.5)
('666884444', '3 ', 40.0)
('453453453', '1 ', 20.0)
('453453453', '2 ', 20.0)
('999887777', '30', 30.0)
('987987987', '10', 35.0)
('987987987', '30', 5.0)
('987654321', '30', 20.0)
('987654321', '20', 15.0)
('888665555', '20', None)
('999887777', '10', 5.0)
